#!/bin/bash
echo "Enter a number"
read a
echo "Enter another number"
read b
echo "What do you want to do? (1 to 4)"
echo "1) Addition"
echo "2) Subtraction"
echo "3) Multiplication"
echo "4) Division"
echo "Enter your choice"
read n
case "$n" in
1) echo "The sum of $a and $b is `expr $a + $b`";;
2) echo "The Difference between $a and $b is `expr $a - $b`";;
3) echo "The Product of the $a and $b is `expr $a \* $b`";;
4) echo "The Division of $a by $b is `expr $a / $b`";;
esac


OUTPUT:
Enter a number
2
Enter another number
1
What do you want to do? (1 to 4)
1) Addition
2) Subtraction
3) Multiplication
4) Division
Enter your choice
1
The sum of 2 and 1 is 3
