#!/bin/bash
echo "Enter a 5 digit number"
read n
num=0
while [ $n -gt 0 ]
do
num=$(expr $num \* 10)
a=$(expr $n % 10)
num=$(expr $num + $a)
n=$(expr $n / 10)
done
echo "Reversed number is" $num


OUTPUT:
Enter a 5 digit number
12345
Reversed number is 54321
