#!/bin/bash
echo "Enter the first number:"
read a
echo "Enter the second number:"
read b
echo "Enter the third number:"
read c
echo "Enter the fourth number:"
read d

sum=$(($a + $b + $c + $d))
avg=$(echo `expr $sum / 4 ` )
prod=$(($a * $b * $c * $d))

echo "The sum of these numbers is: " $sum
echo "The average of these numbers is: " $avg
echo "The product of these numbers is: " $prod


OUTPUT:
Enter the first number:
13
Enter the second number:
5
Enter the third number:
10
Enter the fourth number:
9
The sum of these numbers is:  37
The average of these numbers is:  9
The product of these numbers is:  5850
