#!/bin/bash
echo "Enter an integer number"
read n
a=1
echo "Numbers from $a to $n are:"
while [ $a -le $n ]
do
echo "$a"
a=`expr $a + 1`
done


OUTPUT:
Enter an integer number
3
Numbers from 1 to 3 are:
1
2
3
