#!/bin/bash
echo Enter a year
read leap
echo taking year as $leap
if [ `expr $leap % 400` -eq 0 ]
then
echo it is a leap year
elif [ `expr $leap % 100` -eq 0 ]
then
echo it is not a leap year
elif [ `expr $leap % 4` -eq 0 ]
then
echo it is a leap year
else
echo it is not a leap year
fi


OUTPUT:
Enter a year
2004
taking year as 2004
it is a leap year
