#!/bin/bash
echo "Enter mark 1:"
read m1
echo "Enter mark 2:"
read m2
echo "Enter mark 3:"
read m3
total=`expr $m1 + $m2 + $m3`
echo "Total Marks:"$total
percentage=`expr $total / 3`
echo "Percentage:" $percentage %
if [ $percentage -ge 90 ]
then
echo "S grade"
elif [ $percentage -ge 80 ]
then
echo "A grade"
elif [ $percentage -ge 70 ]
then
echo "B grade"
elif [ $percentage -ge 50 ]
then
echo "C grade"
else
echo "Failed"
fi


OUTPUT:
Enter mark 1:
23
Enter mark 2:
71
Enter mark 3:
42
Total Marks:136
Percentage: 45 %
Failed
